### ISSUE TITLE
POST Request Body

### ISSUE THREAD

**Issue by jonathanrobie** [monotasker/specifications#7]
The POST request body is underspecified.  What are the contents?

**Comment by monotasker** [comment]
Thanks for the question Jonathan. I'm wondering what other information you're looking for. For the Documents endpoint my proposal says this: 

>The body of the POST request must be a properly formed `<TEI>` root node containing TEI compliant XML. See the further specifications under "Default Scheme" above. Note that in most cases the actual text to be inserted is the __contents__ of the inner `<fragment>` element in the request body. The only exception to this rule is where no structural segment has yet been created for a document, in which case the entire `<TEI>` rootnode (along with all its contents) will be accepted as the initial form of the document.

For the Collections endpoint I say this:

>The request body must be valid JSON-LD, following the scheme set out in the core specification for the Collections endpoint. The minimum required terms for each item to be created are:

| Term  | Description    |
| ----- |--------------- |
| `title`         | a single string                                |
| `@id`           | the unique identifier of the item being created|
| `@type`         | a string with one of the two values "Collection" and "Resource"                  |
| `totalItems`    | the number of children contained by the new item at its creation |
| `dts:citeDepth` | the maximum depth of a readable resource (required only when creating a Resource item). |

>If children of the new top-level item are to be created, their metadata should be included as a list under the `member` term.

>The JSON object must also begin with the `@context` property, setting the default vocabulary to Hydra and providing DCT, TEI and DTS namespace prefixes. This only needs to be included once at the top level of the JSON object. If children are included under `member`, the `@context` is not repeated for each child.

In both cases I'm assuming that the user has read the core docs for the endpoint, so I'm not duplicating everything said there. But is there specific information that you see missing from one of these?

**Comment by jonathanrobie** [comment]
Hmmmm, I think I read this too quickly trying to rush and get ready for a meeting.  Apologies - I am closing this now.
